### PR TITLE
Carthage compatability/XCTest for tests

### PR DESCRIPTION
**Pull request by jamezilla**
Sorry this pull request is a bit of a mess. I had to pretty much recreate the workspace and project files to get everything working. I'm submitting this for comments, since I'm sure it will need some review and changes.

Major changes:
- modernized project file
- target for building a dynamic framework
- works with Carthage
- ported all the tests to XCTest

The demo app works, but it looks like it could use some love to work with iPhone 6+.

I tried to run the crayola script, but it failed. I don't think it had to do with any of my changes, though. I think it might be some outdated js dependencies. I'm not familiar with npm/node, so I didn't look into it very deeply. Here's the stack trace:

```
npm install
npm WARN colorScripts@0.0.0 No description
npm WARN colorScripts@0.0.0 No repository field.
npm WARN colorScripts@0.0.0 No license field.
node generateCrayolaHash.js
/Users/jamhughes/src/EDColor/Scripts/node_modules/jsdom/lib/jsdom/level1/core.js:418
  set nodeName() { throw new core.DOMException();},
              ^^

SyntaxError: Setter must have exactly one formal parameter.
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/jamhughes/src/EDColor/Scripts/node_modules/jsdom/lib/jsdom/level2/core.js:1:94)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
make: *** [crayola] Error 1
```

Probably the most controversial thing I did was remove the Podfile. I just couldn't reconcile it with the desire to get a dynamic framework built. I did create a new project/Podfile and successfully installed EDColor from my repository using this Podfile:

```
platform :ios, '8.0'
use_frameworks!

xcodeproj 'Temp/Temp.xcodeproj'

target 'Temp' do
  pod 'EDColor', :git => 'https://github.com/jamezilla/color.git', :branch => 'carthage_compat'
end

```

Any feedback welcome!

### CODE REVIEW

**Comment by thisandagain** [comment]
That's a big PR! Thank you and I'll take a look. :+1: 

Re: the crayola script. Good catch ... that is in need of an update too. I'll take a look during review.

**Comment by jamezilla** [comment]
Sorry... one more comment. I did not update the CONTRIBUTING.md docs. Before I go in there and start trashing things, I thought I would get some general feedback from you guys.

**Comment by dblock** [comment]
The Podfile is there to create the workspace, it looks like you've re-created the whole thing by hand? That sounds like a lot more work. There's no more CI working here, at the very least that needs to be fixed.

Is it possible to accomplish these things one-by-one without actually changing the structure of the project? Dynamic frameworks & al? Maybe @orta can pitch in on how people do it these days?

**Comment by orta** [comment]
Updating any project to support frameworks via Carthage is gonna be a destructive PR, not really a way to do it incrementally as the tool has a pretty limited set of expectations. Nowadays I'd use `pod lib create`'s structure to build libraries which are compatible for it, but even in that case it would still be a drastic change from the current setup.

**Comment by dblock** [comment]
But we want a top level Podfile to get everything Cocapods-enabled, right?

**Comment by orta** [comment]
Well, this PR is about un-doing the work CP does automatically and having it done manually in the Xcode project. You shouldn't need to have a Podfile if it's set up that way. So long as you have a Podspec in the root, people can continue using forks etc.

**Comment by dblock** [comment]
Ok, I get this now. First, thanks for your work @jamezilla.

I am not against Carthage and it would be nice if this library worked with it, but this introduces a lot of work for everyone on this project moving forward, @thisandagain it's of course your call - my 0.02c to begin considering merging this PR is that we want a working CI in this pull request.

**Comment by jamezilla** [comment]
I'm happy to update the CI yml file. My oversight.

> The Podfile is there to create the workspace, it looks like you've re-created the whole thing by hand? That sounds like a lot more work.
File > New > Workspace... Drag the old project files in. That's about it.

You don't even technically need a workspace. It just conceptually groups the two project files together. You can open either project file independently, compile, and run. The workspace isn't really doing anything.

@orta I just looked over the `pod lib create` [documentation](https://guides.cocoapods.org/making/using-pod-lib-create.html). I think there are some good ideas in there, but it seems to be awfully pod-centric - especially compared to the current master repo. For example, all the source code goes under Pods/Classes. This makes it very unintuitive to figure out how to use the source directly (sans CP), or with Carthage. Of course, I'm not the project maintainer, so I'll bend with the wind. Let me know what you all prefer. I'm happy to make any changes.

> introduces a lot of work for everyone on this project moving forward

@dblock could you elaborate on this a bit? I suppose it's true that there is now a target to build the framework, and that target will have to be maintained. But otherwise, it would seem this PR reduces overhead. No require cocoapod dependencies. No OCTest dependencies. Anyone can pull and run the project without additional steps. It's very easy to dip your toe in the waters without having to ramp up on a whole slew of tools (apart from xcode).

**Comment by dblock** [comment]
I don't think we should be having a Carthrage vs. CocoaPods debate here, @thisandagain will decide what he wants.

**Comment by dblock** [comment]
Sorry didn't mean to close this, accidental click.

**Comment by thisandagain** [comment]
I really do appreciate the intent behind some of the design decisions Cartage has made. That said, I think I agree with @dblock and @orta 's sentiments that this would add more of a maintenance burden on the project and breaking CI is a blocker for me. @jamezilla one of your comments that I would absolutely like to address is:

> all the source code goes under Pods/Classes. This makes it very unintuitive to figure out how to use the source directly (sans CP), or with Carthage

I think this is a great point and we should expand the documentation to cover both of these use-cases. In addition, I think updating the project files and migrating to XCTest is long overdue. 

@jamezilla I'm curious how would you feel about the following scope:
- Keep the existing CP structure (Podfile, workspace, etc.)
- Add documentation to cover "Installing without CocoaPods" and "Installing with Carthage"
- Update the XCode project
- Migrate tests to XCTest
- Update `crayola` build scripts to work with newer versions of node (we can handle this separately)

**Comment by jamezilla** [comment]
I think it is possible to reconcile the Carthage compatibility with the pod dependency, but it will result in a very confusing and needlessly complicated setup. You’d effectively have two build systems; one bootstrapped by a `pod install` and the other which is just pure Xcode. You’d use one in certain cases and the other in certain cases. I think it’s better not to conflate ‘build’ and ‘package’. The inability to simply add Carthage compatibility to the project is a symptom that the two are too tightly coupled.

Carthage has one requirement: a project file with a shared target which builds a dynamic framework. The shared framework target is analogous to the podspec file, or Package.swift for the swift package manager. It just happens to piggy-back on the native xcode definition of how to build the code instead of a third party specification file.

I also want to clear up some confusion. There's nothing about the PR which could be framed as Carthage vs. cocoapods. I'm not sure how that crept into the conversation. The project still supports both package managers - in the way every user of cocoapods and every user of Carthage expects. If anything this PR is more agnostic to package managers than the current master branch. In fact, I’m using this code in a substantial work-related project as a cocoapod. I want it to work with cocoapods.

If you guys can agree that adding a shared framework target to the project is beneficial, then I'm willing to bang this PR into whatever shape you want. I’ll even work around your desire to have the `pod install` dependency. But I think once you work with it you’ll agree it’s awkward and a far greater maintenance burden. If the shared framework target is the sticking point, then I'm afraid this PR is dead in the water.

**Comment by dblock** [comment]
@jamezilla The reason why this PR was framed as Cartage vs. Cocoapods is because you removed the latter, which wasn't necessary for the other changes AFAIK.

Thanks for bringing this PR into a :green_book: state. I don't think putting back CocoaPods just for the sake of it makes any sense from here, I'd be OK if this got merged, and thanks for your efforts. Will leave it to @thisandagain.

**Comment by dblock** [comment]
Something I didn't think about is that we no longer have anything in the build process that ensures that the library can be used via CocoaPods. Not sure if it's a problem.

**Pull request closed without merging**
